-- Apply after paynet_payments.sql (shared usage) and paddle_payments.sql.
-- Paddle's tables/functions remain intact. MAIB grants are isolated from legacy resets.
begin;
create table if not exists public.maib_payment_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  environment text not null check (environment in ('sandbox','production')),
  request_key uuid not null,
  product_key text not null,
  amount_minor integer not null check (amount_minor > 100),
  currency_code text not null default 'MDL' check (currency_code = 'MDL'),
  grants jsonb not null,
  language text not null default 'ro' check (language in ('ro','ru')),
  return_to text not null default '/profile',
  status text not null default 'pending' check (status in ('pending','registered','creation_unknown','paid','partially_refunded','refunded','failed','canceled','expired')),
  checkout_id uuid unique,
  checkout_url text,
  payment_id uuid unique,
  refunded_minor integer not null default 0 check (refunded_minor >= 0 and refunded_minor <= amount_minor),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  next_check_at timestamptz not null default now(),
  lease_until timestamptz,
  lease_token uuid,
  last_error text,
  unique (user_id, environment, request_key)
);
create index if not exists maib_orders_reconcile on public.maib_payment_orders(environment,next_check_at);
create index if not exists maib_orders_user on public.maib_payment_orders(user_id,created_at desc,id desc);
create table if not exists public.maib_credit_grants (
  order_id uuid not null references public.maib_payment_orders(id),
  user_id uuid not null references auth.users(id) on delete cascade,
  feature_key text not null check (feature_key in ('sale_estimate','rent_estimate','listing_analysis','cadastru_lookup','yield_calculator','pdf_report')),
  remaining_uses integer not null check (remaining_uses >= 0),
  total_granted integer not null check (total_granted > 0),
  total_used integer not null default 0 check (total_used >= 0),
  overridden boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (order_id,feature_key),
  check (remaining_uses + total_used <= total_granted)
);
create index if not exists maib_grants_user on public.maib_credit_grants(user_id,feature_key,created_at,order_id);
create table if not exists public.maib_callback_events (
  id bigint generated by default as identity primary key,
  delivery_hash text not null unique,
  order_id uuid references public.maib_payment_orders(id),
  payload jsonb not null,
  processed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now()
);
create index if not exists maib_callback_order on public.maib_callback_events(order_id);
create table if not exists public.maib_refund_attempts (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.maib_payment_orders(id),
  refund_id uuid unique,
  amount_minor integer not null check (amount_minor > 0),
  reason text not null check (length(reason) between 1 and 500),
  status text not null default 'submitting' check (status in ('submitting','unknown','Created','Requested','Accepted','Rejected','Manual')),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists maib_refund_order on public.maib_refund_attempts(order_id,created_at desc);
create unique index if not exists maib_one_open_refund on public.maib_refund_attempts(order_id)
  where status in ('submitting','unknown','Created','Requested','Manual');

-- Unified read interfaces. Never write through these views.
create or replace view public.payment_orders_all with (security_invoker=true) as
select id,user_id,product_key,status,amount_minor,currency_code,paid_at,created_at,
  'paddle'::text provider,'legacy'::text environment,paddle_transaction_id transaction_id,
  paddle_subscription_id subscription_id,paddle_transaction_id,paddle_subscription_id,
  0::integer refunded_minor,null::text refund_status
from public.paddle_payment_orders
union all
select o.id,o.user_id,o.product_key,o.status,o.amount_minor,o.currency_code,o.paid_at,o.created_at,
  'maib',o.environment,o.payment_id::text,null::text,null::text,null::text,o.refunded_minor,
  (select r.status from public.maib_refund_attempts r where r.order_id=o.id order by r.created_at desc,r.id desc limit 1)
from public.maib_payment_orders o;
create or replace view public.reporting_payment_orders with (security_invoker=true) as
select * from public.payment_orders_all where provider='paddle' or environment='production';
create or replace view public.user_feature_credit_balances with (security_invoker=true) as
select user_id,feature_key,sum(remaining_uses)::integer remaining_uses,
  sum(total_granted)::integer total_granted,sum(total_used)::integer total_used
from (
  select user_id,feature_key,remaining_uses,total_granted,total_used from public.user_feature_credits
  union all
  select user_id,feature_key,remaining_uses,total_granted,total_used from public.maib_credit_grants where not overridden
) c group by user_id,feature_key;
create or replace view public.reporting_feature_credit_balances with (security_invoker=true) as
select user_id,feature_key,sum(remaining_uses)::integer remaining_uses
from (
  select user_id,feature_key,remaining_uses from public.user_feature_credits
  union all
  select g.user_id,g.feature_key,g.remaining_uses from public.maib_credit_grants g
    join public.maib_payment_orders o on o.id=g.order_id where not g.overridden and o.environment='production'
) c group by user_id,feature_key;

alter table public.payment_checkout_events add column if not exists provider text;
alter table public.payment_checkout_events add column if not exists maib_order_id uuid references public.maib_payment_orders(id) on delete set null;

alter table public.payment_checkout_events drop constraint if exists payment_checkout_events_type_check;
alter table public.payment_checkout_events add constraint payment_checkout_events_type_check
  check (event_type in ('checkout_popup_opened','checkout_page_opened','pricing_page_opened','checkout_order_created'));

create or replace function public.apply_maib_payment(
  p_order_id uuid,p_environment text,p_checkout_id uuid,p_payment_id uuid,
  p_amount_minor integer,p_currency text,p_status text,p_refunded_minor integer default 0,p_paid_at timestamptz default now()
) returns void language plpgsql set search_path=public as $$
declare o public.maib_payment_orders%rowtype; f text; n text;
begin
  select * into o from public.maib_payment_orders where id=p_order_id;
  if not found or o.user_id is null then raise exception 'order not found'; end if;
  perform pg_advisory_xact_lock(hashtext(o.user_id::text),hashtext('payment-credits'));
  select * into o from public.maib_payment_orders where id=p_order_id for update;
  if o.environment<>p_environment or o.amount_minor<>p_amount_minor or o.currency_code<>p_currency
    or p_payment_id is null or p_checkout_id is null
    or (o.checkout_id is not null and o.checkout_id<>p_checkout_id)
    or (o.payment_id is not null and o.payment_id<>p_payment_id) then raise exception 'payment mismatch'; end if;
  if p_status not in ('paid','partially_refunded','refunded') then raise exception 'invalid payment status'; end if;
  if p_refunded_minor<0 or p_refunded_minor>o.amount_minor
    or (p_status='refunded' and p_refunded_minor<>o.amount_minor) then raise exception 'invalid refund amount'; end if;
  if o.status='refunded' then return; end if;
  if o.paid_at is null and p_status<>'refunded' then
    for f,n in select key,value from jsonb_each_text(o.grants) loop
      insert into public.maib_credit_grants(order_id,user_id,feature_key,remaining_uses,total_granted)
        values(o.id,o.user_id,f,n::integer,n::integer) on conflict do nothing;
    end loop;
  end if;
  update public.maib_payment_orders set checkout_id=p_checkout_id,payment_id=p_payment_id,
    status=case when p_status='refunded' then 'refunded'
      when greatest(refunded_minor,p_refunded_minor)>0 then 'partially_refunded' else 'paid' end,
    refunded_minor=greatest(refunded_minor,p_refunded_minor),paid_at=coalesce(paid_at,p_paid_at,now()),
    updated_at=now(),last_error=null where id=o.id;
  if p_status='refunded' then
    update public.maib_credit_grants set remaining_uses=0 where order_id=o.id;
    update public.maib_refund_attempts set status='Accepted',updated_at=now()
      where order_id=o.id and status in ('submitting','unknown','Created','Requested','Manual');
  end if;
end $$;

create or replace function public.reserve_maib_refund(p_order_id uuid,p_amount_minor integer,p_reason text)
returns uuid language plpgsql set search_path=public as $$
declare o public.maib_payment_orders%rowtype; rid uuid;
begin
  select * into o from public.maib_payment_orders where id=p_order_id for update;
  if not found or o.status not in ('paid','partially_refunded') or o.payment_id is null
    or p_amount_minor<>o.amount_minor-o.refunded_minor or p_amount_minor<=0 then raise exception 'order is not refundable'; end if;
  insert into public.maib_refund_attempts(order_id,amount_minor,reason) values(o.id,p_amount_minor,p_reason) returning id into rid;
  update public.maib_payment_orders set next_check_at=now() where id=o.id;
  return rid;
end $$;

create or replace function public.claim_maib_orders(p_environment text,p_limit integer default 20)
returns setof public.maib_payment_orders language plpgsql set search_path=public as $$
begin
  return query update public.maib_payment_orders o set lease_until=now()+interval '5 minutes',lease_token=gen_random_uuid()
  where o.id in (select q.id from public.maib_payment_orders q
    where q.environment=p_environment and q.next_check_at<=now()
      and (q.lease_until is null or q.lease_until<now())
      and (q.status in ('pending','registered','creation_unknown','paid','partially_refunded')
        or exists(select 1 from public.maib_refund_attempts r where r.order_id=q.id and r.status in ('submitting','unknown','Created','Requested','Manual')))
    order by q.next_check_at limit least(greatest(p_limit,1),100) for update skip locked)
  returning o.*;
end $$;

-- Same public usage contract; legacy balance first, then oldest MAIB grant.
create or replace function public.consume_user_feature_credit(p_user_id uuid,p_feature_key text,p_idempotency_key text,p_metadata jsonb default '{}'::jsonb)
returns table(allowed boolean,usage_event_id uuid,source text,remaining_uses integer,reason text)
language plpgsql set search_path=public as $$
declare old public.user_feature_usage_events%rowtype; grant_order uuid; usage_id uuid; consumed boolean;
begin
  if p_user_id is null or nullif(trim(p_idempotency_key),'') is null or p_feature_key not in
    ('sale_estimate','rent_estimate','listing_analysis','cadastru_lookup','yield_calculator','pdf_report') then raise exception 'invalid usage request'; end if;
  perform pg_advisory_xact_lock(hashtext(p_user_id::text),hashtext('payment-credits'));
  select * into old from public.user_feature_usage_events e where e.user_id=p_user_id and e.feature_key=p_feature_key and e.idempotency_key=p_idempotency_key;
  if found then return query select true,old.id,old.source,null::integer,'already_consumed'::text; return; end if;
  update public.user_feature_credits c set remaining_uses=c.remaining_uses-1,total_used=c.total_used+1
    where c.user_id=p_user_id and c.feature_key=p_feature_key and c.remaining_uses>0;
  consumed:=found;
  if not consumed then
    select g.order_id into grant_order from public.maib_credit_grants g
      where g.user_id=p_user_id and g.feature_key=p_feature_key and g.remaining_uses>0 and not g.overridden
      order by g.created_at,g.order_id limit 1 for update;
    if found then
      update public.maib_credit_grants g set remaining_uses=g.remaining_uses-1,total_used=g.total_used+1
        where g.order_id=grant_order and g.feature_key=p_feature_key;
      consumed:=true;
    end if;
  end if;
  if not consumed then return query select false,null::uuid,null::text,0,'no_credit'::text; return; end if;
  insert into public.user_feature_usage_events(user_id,feature_key,source,idempotency_key,metadata)
    values(p_user_id,p_feature_key,'paid_credit',p_idempotency_key,
      coalesce(p_metadata,'{}'::jsonb)||jsonb_build_object('payment_provider',case when grant_order is null then 'legacy' else 'maib' end,'maib_order_id',grant_order)) returning id into usage_id;
  return query select true,usage_id,'paid_credit'::text,coalesce(b.remaining_uses,0),'consumed'::text
    from public.user_feature_credit_balances b where b.user_id=p_user_id and b.feature_key=p_feature_key;
end $$;

-- Explicit admin override: replace both sources; preserve usage for bulk balances.
create or replace function public.override_payment_credits(p_user_id uuid,p_grants jsonb,p_preserve_used boolean default false,p_clear boolean default false)
returns void language plpgsql set search_path=public as $$
declare f text; n integer; used integer;
begin
  perform pg_advisory_xact_lock(hashtext(p_user_id::text),hashtext('payment-credits'));
  for f in select unnest(array['sale_estimate','rent_estimate','listing_analysis','cadastru_lookup','yield_calculator','pdf_report']) loop
    n:=coalesce((p_grants->>f)::integer,0);
    if n<0 or n>1000 then raise exception 'invalid grant'; end if;
    select coalesce(b.total_used,0) into used from public.user_feature_credit_balances b where b.user_id=p_user_id and b.feature_key=f;
    update public.maib_credit_grants set remaining_uses=0,overridden=true where user_id=p_user_id and feature_key=f;
    if p_clear then delete from public.user_feature_credits where user_id=p_user_id and feature_key=f;
    else
      used:=case when p_preserve_used then coalesce(used,0) else 0 end;
      insert into public.user_feature_credits(user_id,feature_key,remaining_uses,total_used,total_granted)
        values(p_user_id,f,n,used,n+used) on conflict(user_id,feature_key) do update
        set remaining_uses=excluded.remaining_uses,total_used=excluded.total_used,total_granted=excluded.total_granted;
    end if;
  end loop;
end $$;

do $$ declare t text; sig text; begin
  foreach t in array array['maib_payment_orders','maib_credit_grants','maib_callback_events','maib_refund_attempts'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on public.%I from public,anon,authenticated',t);
    execute format('grant all on public.%I to service_role',t);
  end loop;
  foreach t in array array['payment_orders_all','reporting_payment_orders','user_feature_credit_balances','reporting_feature_credit_balances'] loop
    execute format('revoke all on public.%I from public,anon,authenticated',t);
    execute format('grant select on public.%I to service_role',t);
  end loop;
  foreach sig in array array[
    'apply_maib_payment(uuid,text,uuid,uuid,integer,text,text,integer,timestamptz)',
    'reserve_maib_refund(uuid,integer,text)','claim_maib_orders(text,integer)',
    'consume_user_feature_credit(uuid,text,text,jsonb)','override_payment_credits(uuid,jsonb,boolean,boolean)'
  ] loop
    execute 'revoke all on function public.'||sig||' from public,anon,authenticated';
    execute 'grant execute on function public.'||sig||' to service_role';
  end loop;
end $$;
grant usage,select on sequence public.maib_callback_events_id_seq to service_role;
notify pgrst,'reload schema';
commit;
