-- ============================================================
-- Paynet one-time payments MVP schema
-- Run this in Supabase SQL Editor
-- ============================================================

create extension if not exists pgcrypto;

create or replace function public.touch_paynet_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ============================================================
-- payment_orders - one Paynet checkout attempt
-- ============================================================

create table if not exists public.payment_orders (
  id                    uuid primary key default gen_random_uuid(),
  invoice_no            bigint generated by default as identity unique not null,
  user_id               uuid references auth.users(id) on delete set null,
  product_key           text not null,
  amount_minor          integer not null,
  currency              integer not null default 498,
  status                text not null default 'pending',
  paynet_payment_id     bigint unique,
  paynet_status         integer,
  paynet_signature      text,
  paynet_registered_at  timestamptz,
  paid_at               timestamptz,
  credit_grants         jsonb not null default '{}'::jsonb,
  canceled_at           timestamptz,
  expires_at            timestamptz,
  language              text,
  customer_snapshot     jsonb not null default '{}'::jsonb,
  request_payload       jsonb not null default '{}'::jsonb,
  response_payload      jsonb not null default '{}'::jsonb,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  constraint payment_orders_product_check
    check (product_key in (
      'standard_pack',
      'pro_pack',
      'listing_analysis_single',
      'cadastru_lookup_single',
      'yield_calculator_single',
      'pdf_report_single'
    )),
  constraint payment_orders_amount_check
    check (amount_minor > 0),
  constraint payment_orders_currency_check
    check (currency = 498),
  constraint payment_orders_status_check
    check (status in ('pending', 'registered', 'paid', 'canceled', 'expired', 'failed')),
  constraint payment_orders_paynet_status_check
    check (paynet_status is null or paynet_status in (1, 2, 3, 4)),
  constraint payment_orders_language_check
    check (language is null or language in ('ro', 'ru', 'en'))
);

create index if not exists idx_payment_orders_user_created
  on public.payment_orders (user_id, created_at desc);

create index if not exists idx_payment_orders_status_created
  on public.payment_orders (status, created_at desc);

create index if not exists idx_payment_orders_invoice
  on public.payment_orders (invoice_no);

create index if not exists idx_payment_orders_paynet_payment
  on public.payment_orders (paynet_payment_id);

drop trigger if exists trg_payment_orders_updated_at on public.payment_orders;
create trigger trg_payment_orders_updated_at
before update on public.payment_orders
for each row execute function public.touch_paynet_updated_at();

-- ============================================================
-- paynet_notifications - raw Paynet callback audit and idempotency
-- ============================================================

create table if not exists public.paynet_notifications (
  id                    bigserial primary key,
  event_id              bigint unique,
  event_type            text,
  event_date            timestamptz,
  order_id              uuid references public.payment_orders(id) on delete set null,
  paynet_payment_id     bigint,
  invoice_no            bigint,
  merchant_code         text,
  payment_customer      text,
  amount_minor          integer,
  hash_header           text,
  hash_valid            boolean not null default false,
  payload               jsonb not null default '{}'::jsonb,
  processed_at          timestamptz,
  processing_error      text,
  created_at            timestamptz not null default now(),

  constraint paynet_notifications_event_type_check
    check (event_type is null or lower(event_type) = 'paid'),
  constraint paynet_notifications_amount_check
    check (amount_minor is null or amount_minor > 0)
);

create index if not exists idx_paynet_notifications_order_created
  on public.paynet_notifications (order_id, created_at desc);

create index if not exists idx_paynet_notifications_invoice_created
  on public.paynet_notifications (invoice_no, created_at desc);

create index if not exists idx_paynet_notifications_payment_created
  on public.paynet_notifications (paynet_payment_id, created_at desc);

create index if not exists idx_paynet_notifications_hash_valid_created
  on public.paynet_notifications (hash_valid, created_at desc);

-- ============================================================
-- user_feature_credits - aggregate purchased credits by user/feature
-- ============================================================

create table if not exists public.user_feature_credits (
  user_id           uuid not null references auth.users(id) on delete cascade,
  feature_key       text not null,
  remaining_uses    integer not null default 0,
  total_granted     integer not null default 0,
  total_used        integer not null default 0,
  updated_at        timestamptz not null default now(),
  created_at        timestamptz not null default now(),

  primary key (user_id, feature_key),
  constraint user_feature_credits_feature_check
    check (feature_key in (
      'sale_estimate',
      'rent_estimate',
      'listing_analysis',
      'cadastru_lookup',
      'yield_calculator',
      'pdf_report'
    )),
  constraint user_feature_credits_count_check
    check (
      remaining_uses >= 0
      and total_granted >= 0
      and total_used >= 0
    )
);

create index if not exists idx_user_feature_credits_active
  on public.user_feature_credits (user_id, feature_key)
  where remaining_uses > 0;

drop trigger if exists trg_user_feature_credits_updated_at on public.user_feature_credits;
create trigger trg_user_feature_credits_updated_at
before update on public.user_feature_credits
for each row execute function public.touch_paynet_updated_at();

-- ============================================================
-- user_feature_usage_events - idempotent feature consumption log
-- ============================================================

create table if not exists public.user_feature_usage_events (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  feature_key       text not null,
  source_order_id   uuid references public.payment_orders(id) on delete set null,
  source            text not null,
  idempotency_key   text not null,
  metadata          jsonb not null default '{}'::jsonb,
  created_at        timestamptz not null default now(),

  constraint user_feature_usage_events_feature_check
    check (feature_key in (
      'sale_estimate',
      'rent_estimate',
      'listing_analysis',
      'cadastru_lookup',
      'yield_calculator',
      'pdf_report'
    )),
  constraint user_feature_usage_events_source_check
    check (source in ('free_monthly', 'paid_credit', 'admin_adjustment')),
  constraint user_feature_usage_events_idempotency_check
    check (length(trim(idempotency_key)) > 0),
  constraint user_feature_usage_events_unique
    unique (user_id, feature_key, idempotency_key)
);

create index if not exists idx_user_feature_usage_events_user_created
  on public.user_feature_usage_events (user_id, created_at desc);

create index if not exists idx_user_feature_usage_events_feature_created
  on public.user_feature_usage_events (feature_key, created_at desc);

create index if not exists idx_user_feature_usage_events_order
  on public.user_feature_usage_events (source_order_id);

-- ============================================================
-- RPC helpers for payment grants and credit consumption
-- ============================================================

create or replace function public.grant_user_feature_credits(
  p_user_id uuid,
  p_feature_key text,
  p_uses_count integer
)
returns void
language plpgsql
as $$
begin
  if p_user_id is null then
    raise exception 'p_user_id is required';
  end if;

  if p_feature_key not in (
    'sale_estimate',
    'rent_estimate',
    'listing_analysis',
    'cadastru_lookup',
    'yield_calculator',
    'pdf_report'
  ) then
    raise exception 'unknown feature key: %', p_feature_key;
  end if;

  if p_uses_count <= 0 then
    raise exception 'p_uses_count must be positive';
  end if;

  insert into public.user_feature_credits (
    user_id,
    feature_key,
    remaining_uses,
    total_granted
  ) values (
    p_user_id,
    p_feature_key,
    p_uses_count,
    p_uses_count
  )
  on conflict (user_id, feature_key) do update set
    remaining_uses = public.user_feature_credits.remaining_uses + excluded.remaining_uses,
    total_granted = public.user_feature_credits.total_granted + excluded.total_granted;
end;
$$;

create or replace function public.grant_payment_order_feature_credits(
  p_order_id uuid,
  p_feature_key text,
  p_uses_count integer
)
returns table (
  granted boolean,
  remaining_uses integer
)
language plpgsql
as $$
declare
  v_order public.payment_orders%rowtype;
  v_remaining_uses integer;
begin
  if p_feature_key not in (
    'sale_estimate',
    'rent_estimate',
    'listing_analysis',
    'cadastru_lookup',
    'yield_calculator',
    'pdf_report'
  ) then
    raise exception 'unknown feature key: %', p_feature_key;
  end if;

  if p_uses_count <= 0 then
    raise exception 'p_uses_count must be positive';
  end if;

  select *
    into v_order
  from public.payment_orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'payment order not found: %', p_order_id;
  end if;

  if v_order.status <> 'paid' then
    raise exception 'payment order % is not paid', p_order_id;
  end if;

  if v_order.user_id is null then
    raise exception 'payment order % has no user_id', p_order_id;
  end if;

  if v_order.credit_grants ? p_feature_key then
    select credits.remaining_uses
      into v_remaining_uses
    from public.user_feature_credits credits
    where credits.user_id = v_order.user_id
      and credits.feature_key = p_feature_key;

    granted := false;
    remaining_uses := coalesce(v_remaining_uses, 0);
    return next;
    return;
  end if;

  perform public.grant_user_feature_credits(v_order.user_id, p_feature_key, p_uses_count);

  update public.payment_orders
  set credit_grants = credit_grants || jsonb_build_object(p_feature_key, p_uses_count)
  where id = v_order.id;

  select credits.remaining_uses
    into v_remaining_uses
  from public.user_feature_credits credits
  where credits.user_id = v_order.user_id
    and credits.feature_key = p_feature_key;

  granted := true;
  remaining_uses := coalesce(v_remaining_uses, 0);
  return next;
end;
$$;

create or replace function public.complete_paynet_payment(
  p_invoice_no bigint,
  p_paynet_payment_id bigint,
  p_amount_minor integer,
  p_paynet_status integer,
  p_payload jsonb default '{}'::jsonb,
  p_paid_at timestamptz default now()
)
returns table (
  order_id uuid,
  product_key text
)
language plpgsql
as $$
declare
  v_order public.payment_orders%rowtype;
begin
  if p_paynet_status <> 4 then
    raise exception 'paynet status is not paid: %', p_paynet_status;
  end if;

  select *
    into v_order
  from public.payment_orders
  where invoice_no = p_invoice_no
  for update;

  if not found then
    raise exception 'payment order not found for invoice: %', p_invoice_no;
  end if;

  if v_order.user_id is null then
    raise exception 'payment order % has no user_id', v_order.id;
  end if;

  if v_order.amount_minor <> p_amount_minor then
    raise exception 'amount mismatch for invoice %', p_invoice_no;
  end if;

  if v_order.paynet_payment_id is not null
     and v_order.paynet_payment_id <> p_paynet_payment_id then
    raise exception 'paynet payment id mismatch for invoice %', p_invoice_no;
  end if;

  update public.payment_orders
  set
    status = 'paid',
    paynet_payment_id = coalesce(paynet_payment_id, p_paynet_payment_id),
    paynet_status = p_paynet_status,
    paid_at = coalesce(paid_at, p_paid_at, now()),
    response_payload = coalesce(response_payload, '{}'::jsonb) || coalesce(p_payload, '{}'::jsonb)
  where id = v_order.id
  returning * into v_order;

  -- Product-to-credit mapping stays in app code for the MVP.
  -- The API route should call grant_user_feature_credits() for each mapped feature
  -- after this function confirms and locks the paid order.

  order_id := v_order.id;
  product_key := v_order.product_key;
  return next;
end;
$$;

create or replace function public.consume_user_feature_credit(
  p_user_id uuid,
  p_feature_key text,
  p_idempotency_key text,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  allowed boolean,
  usage_event_id uuid,
  source text,
  remaining_uses integer,
  reason text
)
language plpgsql
as $$
declare
  v_existing public.user_feature_usage_events%rowtype;
  v_usage_id uuid;
  v_remaining_uses integer;
begin
  if p_user_id is null then
    raise exception 'p_user_id is required';
  end if;

  if p_feature_key not in (
    'sale_estimate',
    'rent_estimate',
    'listing_analysis',
    'cadastru_lookup',
    'yield_calculator',
    'pdf_report'
  ) then
    raise exception 'unknown feature key: %', p_feature_key;
  end if;

  if length(trim(coalesce(p_idempotency_key, ''))) = 0 then
    raise exception 'p_idempotency_key is required';
  end if;

  perform pg_advisory_xact_lock(
    hashtext(p_user_id::text),
    hashtext(p_feature_key || ':' || p_idempotency_key)
  );

  select *
    into v_existing
  from public.user_feature_usage_events usage_events
  where usage_events.user_id = p_user_id
    and usage_events.feature_key = p_feature_key
    and usage_events.idempotency_key = p_idempotency_key;

  if found then
    allowed := true;
    usage_event_id := v_existing.id;
    source := v_existing.source;
    remaining_uses := null;
    reason := 'already_consumed';
    return next;
    return;
  end if;

  update public.user_feature_credits credits
  set
    remaining_uses = credits.remaining_uses - 1,
    total_used = credits.total_used + 1
  where credits.user_id = p_user_id
    and credits.feature_key = p_feature_key
    and credits.remaining_uses > 0
  returning credits.remaining_uses into v_remaining_uses;

  if not found then
    allowed := false;
    usage_event_id := null;
    source := null;
    remaining_uses := 0;
    reason := 'no_credit';
    return next;
    return;
  end if;

  insert into public.user_feature_usage_events (
    user_id,
    feature_key,
    source,
    idempotency_key,
    metadata
  ) values (
    p_user_id,
    p_feature_key,
    'paid_credit',
    p_idempotency_key,
    coalesce(p_metadata, '{}'::jsonb)
  )
  returning id into v_usage_id;

  allowed := true;
  usage_event_id := v_usage_id;
  source := 'paid_credit';
  remaining_uses := v_remaining_uses;
  reason := 'consumed';
  return next;
end;
$$;

-- ============================================================
-- Access: payment and credit tables are server-owned for now.
-- API routes should use SUPABASE_SERVICE_KEY and enforce user auth.
-- ============================================================

alter table public.payment_orders enable row level security;
alter table public.paynet_notifications enable row level security;
alter table public.user_feature_credits enable row level security;
alter table public.user_feature_usage_events enable row level security;

revoke all on public.payment_orders from anon, authenticated;
revoke all on public.paynet_notifications from anon, authenticated;
revoke all on public.user_feature_credits from anon, authenticated;
revoke all on public.user_feature_usage_events from anon, authenticated;

grant all on public.payment_orders to service_role;
grant all on public.paynet_notifications to service_role;
grant all on public.user_feature_credits to service_role;
grant all on public.user_feature_usage_events to service_role;
grant usage, select on sequence public.payment_orders_invoice_no_seq to service_role;
grant usage, select on sequence public.paynet_notifications_id_seq to service_role;

revoke execute on function public.grant_user_feature_credits(uuid, text, integer) from public;
revoke execute on function public.grant_payment_order_feature_credits(uuid, text, integer) from public;
revoke execute on function public.complete_paynet_payment(bigint, bigint, integer, integer, jsonb, timestamptz) from public;
revoke execute on function public.consume_user_feature_credit(uuid, text, text, jsonb) from public;

grant execute on function public.grant_user_feature_credits(uuid, text, integer) to service_role;
grant execute on function public.grant_payment_order_feature_credits(uuid, text, integer) to service_role;
grant execute on function public.complete_paynet_payment(bigint, bigint, integer, integer, jsonb, timestamptz) to service_role;
grant execute on function public.consume_user_feature_credit(uuid, text, text, jsonb) to service_role;
